[[themes]]
name = "tokyo_night"
[themes.palette]
foreground = "#a9b1d6"
black = "#32344a"
red = "#f7768e"
#green = "#9ece6a"
green = "#7aa2f7"
yellow = "#e0af68"
#blue = "#7aa2f7"
blue = "#9ece6a"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#787c99"
bright_black = "#444b6a"
bright_red = "#ff7a93"
bright_green = "#b9f27c"
bright_yellow = "#ff9e64"
bright_blue = "#7da6ff"
bright_magenta = "#bb9af7"
bright_cyan = "#0db9d7"
bright_white = "#acb0d0"
